### ISSUE TITLE
Security Advisory event payload is missing the name of the repo for which the advisory was issued

### ISSUE THREAD

**Issue by Abhi347** [octokit/webhooks.js#119]
Hi,
I am not sure whether this is the right place to post this issue (or whether this is intentional), fell free to guide me there.
I am creating a github app for tracking security vulnerabilities in the repos of my organisation. I was checking the security advisory event, but the event payload is missing the repository field for which the advisory was issued. I wanted to create automated issues on repos when the advisory is published, but the missing field makes it really difficult.
Another way would be to fetch security advisories of all the repos in the organisation, but it looks very counter-productive (Not to mention we have around 2K repos in the organisation).

**Comment by gr2m** [comment]
Hi @Abhi347, perfectly fine to report the issue here. Other users might run into the same problem and can follow this issue.

There is not much we can do on our side, but I agree that there probably should be a `"repository"` key in the webhook payload, like many of the other events. 

Can you reach out to https://support.github.com/contact and reference this issue? GitHub Support will be the best team to find the right people to address this issue. If you could keep us posted here, that'd be great!

**Comment by gr2m** [comment]
I'll close the issue as there is nothing actionable here to do, but please keep us posted if support gets back to you
