### ISSUE TITLE
7.11.1 introduces typescript compile error with aggregate-error

### ISSUE THREAD

**Issue by AArnott** [octokit/webhooks.js#235]
#183 introduced a typescript compile break when it added a use of `AggregateError<T>` while still referencing `aggregate-error ^3.0.1`. 3.0.1 does not define a generic `AggregateError<T>` type, which leads octokit 7.11.1 consumers to encounter this typescript compiler error:

```
$ tsc
node_modules/@octokit/webhooks/dist-types/types.d.ts:31:51 - error TS2315: Type 'AggregateError' is not generic.

31 export interface WebhookEventHandlerError extends AggregateError<WebhookError> {
                                                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Found 1 error.
```

Please update project.json to depend on `aggregate-error ^3.1.0` to fix the break and release a new npm package.

**Comment by oscard0m** [comment]
Hi @AArnott, thanks for your opened issue. I just run an `npm upgrade @octokit/webhooks` in my local machine and my `package-lock.json` was upgraded with latest `aggregate-error` version (`3.1.0`). As far as I understand, since `@octokit/webhooks` requires `aggregate-error` version `^3.0.1` it should try to install the latest satisfying the semver notation.

- Could you try running a manual `npm upgrade @octokit/webhooks` and check if `aggregate-error` version gets updated in `package-lock.json`?
- Could be related to a configuration or a bug on `dependabot`? (sounds strange since this is something exhaustively used across the community)

Thanks once again for your opened issue :)

**Comment by oscard0m** [comment]
> Hi @AArnott, thanks for your opened issue. I just run an `npm upgrade @octokit/webhooks` in my local machine and my `package-lock.json` was upgraded with latest `aggregate-error` version (`3.1.0`). As far as I understand, since `@octokit/webhooks` requires `aggregate-error` version `^3.0.1` it should try to install the latest satisfying the semver notation.
> 
> * Could you try running a manual `npm upgrade @octokit/webhooks` and check if `aggregate-error` version gets updated in `package-lock.json`?
> * Could be related to a configuration or a bug on `dependabot`? (sounds strange since this is something exhaustively used across the community)
> 
> Thanks once again for your opened issue :)

@AArnott I've been able to reproduce the issue. Forcing `aggregate-error@3.0.1` in `package-lock.json` (`npm i aggreagate-error@3.0.1`) and later running `npm upgrade @octokit/webhooks` updates to 7.1.1 but does not upgrade `aggreggate-error` package to `3.1.0`, you are right
