### ISSUE TITLE
`pull_request.merged` event listener never invoked

### ISSUE THREAD

**Issue by rr-codes** [octokit/webhooks.js#364]
**What happened?**

`webhooks.on('pull_request.merged', ...)` is never invoked. Instead, the listener for `pull_request.closed` is called.

**What did you expect to happen?**

I expected the listener attached to `pull_request.merged` be called when a pull request is merged.

**What the problem might be**

`merged` isn't even a valid action on the `pull_request` payload. Instead, a pull request is merged if its `action === 'closed'` and `merged === true`. 

Either a special case should be added to get `pull_request.merged` to work, or it should be removed to avoid this bug.

**Comment by gr2m** [comment]
This needs to be fixed in https://github.com/octokit/webhooks. We get the webhook names/actions from parsing https://docs.github.com/en/free-pro-team@latest/developers/webhooks-and-events/webhook-events-and-payloads, `pull_request.merged` looks like a false positive

It should also be fixed via https://github.com/octokit/webhooks/pull/186, but the work on it seems stale right now
