### ISSUE TITLE
remove "debug" property

### ISSUE THREAD

**Issue by gr2m** [octokit/webhooks.js#477]
We introduced a `log` option as a replacement for the `debug` module in https://github.com/octokit/webhooks.js/pull/457. As part of the next breaking release, we shoudl remove the `debug` module altogether.

**Comment by gr2m** [comment]
@G-Rath @oscard0m @wolfy1339 I'd like to remove the `debug` option in preparation for using webhooks as part of the `octokit` package, see https://github.com/octokit/octokit.js/pull/15.

Any other breaking changes we should address as part of v9?

**Comment by wolfy1339** [comment]
Possibly not related, but I think we should split up `@octokit/webhooks-defintions` and then include it in the changes for v9

**Comment by gr2m** [comment]
That doesn't sound like a breaking change?

**Comment by G-Rath** [comment]
we could adjust the `transform` option to require it to return the event + extras, vs technically allowing anything to be returned (i.e strings).

I'm not fussed on how far we actually take this at runtime, since I think it'll be overkill to verify the returned object is most definitely the event by way of checking for every required property + types + etc but we could do a basic `typeof x === 'object'`   assertion.

That's *if* we want to do anything at all at runtime - I'm happy if we just want to say "your transformation should return an extension of the original event object - our types assume you do but we don't actually enforce this at runtime" (which is what we're currently doing)

**Comment by gr2m** [comment]
I agree, I wouldn't do any checks at runtime, just document that it should, and implement the types accordingly. Similarly, we don't implement any client-side validation for all the REST API endpoint methods any more, we just provide the correct types. It has worked out great
