### ISSUE TITLE
type guards for Webhook event types

### ISSUE THREAD

**Issue by retorquere** [octokit/webhooks.js#522]
(I'm here in the assumption that `@octokit/webhooks-definitions` lives in this repo; the npmjs page for `@octokit/webhooks-definitions` points to https://github.com/octokit/webhooks.js)

I have a function that can accept either an `IssueCommentEvent` or an `IssuesEvent`:

```
function body(event: IssueCommentEvent | IssuesEvent) {
  if (...) {
    // tsc knows it is an IssueCommentEvent
  } else if (...) {
    // tsc knows it is an IssuesEvent
  }
}
```

Normally I'd use type guards to inform the typescript compiler which of these two types `event` is, but I don't see anything in the `Event` types that I could use for this. How should I have tsc infer the type?

**Comment by wolfy1339** [comment]
The `IssueCommentEvent` has a `comment` property that you can use to distinguish both types of events from each other.

Although, the Typescript compiler is a lot more finicky and probably won't like that. Since they don't both share a common property that could distinguish from each other.

If you pass in the whole of the event metadata from the webhooks handler, it will tell you which event it is.

```js
webhooks.on(['issue_comment', 'issues'], (event) => {
    if (event.name === 'issue_comment'){
        const payload = event.payload as IssueCommentEvent;
        // Handle issue comment event
    } else {
        const payload = event.payload as IssuesEvent;
        // Handle issues event
    }
})
```

**Comment by retorquere** [comment]
I've tried type guarding on the comment property but tsc wouldn't take the hint. I've settled in just detecting it myself and using explicit typecasts after that.

**Comment by wolfy1339** [comment]
Closing since there's nothing we can do on our side
