### ISSUE TITLE
Backport #72 so it can be used in older versions of Probot

### ISSUE THREAD

**Issue by tcbyrd** [octokit/webhooks.js#73]
Discussed here: https://github.com/octokit/webhooks.js/pull/72#issuecomment-482240630

Some integrations need to be able to use the fix from #72 in older versions of Probot (at least 7.5.0 that I know of), so wanted to discuss here if we need to backport webhooks.js in order to facilitate this.

cc @scepticulous @gimenete @gr2m

**Comment by dennissivia** [comment]
I agree, it would be amazing if we could create two PRs to probot. One to master and one to the 7.x branch and release 7.5.1 of probot with would include the fix in #72 included. This way it is just a patchlevel update for webhook.js and for probot and since the change only fixes a bug, it looks like a good option.

**Comment by gr2m** [comment]
We can update probot 7 to the latest `@ocotkit/webhooks`, I see no reason not to

**Comment by gr2m** [comment]
👉 [probot@7.5.3](https://github.com/probot/probot/releases/tag/v7.5.3%407.x) Does that work?

**Comment by dennissivia** [comment]
> 👉 [probot@7.5.3](https://github.com/probot/probot/releases/tag/v7.5.3%407.x) Does that work?

✅ Works like a charm 👏 
I tested a direct comparison of 7.5.2 and 7.5.3 and that version bump makes the problem go away 💟 

IMO we can close this backport issue 👍

**Comment by gr2m** [comment]
Thanks for checking 👍
